spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect2
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: testamszpi@gmail.com
    password: testAMS!123
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  version: 1.0.0
  swagger-ui:
    path: /api/docs

server:
  port: 10000
  error:
    include-message: always

security:
  jwt:
    token:
      secret-key: "DJASFDNUS812DAMNXMANSDHQHW83183JD18JJ1HFG8JXJ12JSH1XCHBUJ28X2JH12J182XJH1F3H1JS81G7RESHD13H71"
  aes:
    secret-key: "shSHs321ecuredsadD51HdsaACQLOA33sharedsadD51HdsaACQLOA33ACO3482JJ12SHs321ecudsaredaredsadD51HdsaACQLOA33ACO3482JJ12sadD51HdsaACQLOA33ACO3482JJ123DEF1LONGA0AENUGH4dDSAACO348shSHs321ecuredsadD51HdsaACQLOA33ACO3482JJ123DEF1LONGA0AENUGH4dDSA2JJ123DEF1LONGA0AENUGH4dDSA-dA58i1A123FAHFh"